from sympy import (Symbol, symbols,factor, expand, pprint, init_printing, simplify,sin, cos)
x = Symbol('x')
f = x + x + x + 2
print(f)
a = Symbol('Noi')
b = Symbol('Chim')
expr = 3*b + 7*a
print(expr)
print(a.name)
print(b.name)
a, b, c = symbols('a, b, c')
print(a, b, c)
x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
print(s)
p1 = x * (x + 2*x)
print(p1)
p2 = (x + 2)*(y + 3)
print(p2)
print(p2.expand())
p3 = (x + 2)*(y + 3) + (x + 2)*(x - 3)
print(p3)
x = Symbol('x')
y = Symbol('y')
bieuthuc = x**3 - y**3
print(factor(bieuthuc))
bieuthuc = (x - y)*(x**2 + x*y + y**2)
print(expand(bieuthuc))
init_printing(order='rev-lex')
bieuthuc = x**2 - 2*x*y + y**2
pprint(bieuthuc)
bieuthuc1 = factor(bieuthuc)
pprint(bieuthuc1)
bieuthuc = x**2 - x*y + y**2
print(bieuthuc)
giatri = bieuthuc.subs({x: 3, y: 2})
print(giatri)
print(x, y)
giatri = bieuthuc.subs({x: y, y: 3})
print(giatri)
giatri = bieuthuc.subs({y: x}).subs({x: 3})
print(giatri)
bieuthuc_moi = bieuthuc.subs({x: 1 - y})
print(bieuthuc_moi)
dongian = simplify(bieuthuc_moi)
print(dongian)
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
print(bt_moi)